
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Deft": "../../../deft/src/js",
  "Deft.Component": "../../../deft/src/js/event/LiveEventBus.js",
  "Deft.InjectableComponent": "../../../deft/src/js/ioc/Injector.js",
  "Entities.app.App": "../../../Entities/src/app/App.js",
  "Entities.controller.ContentTypesList": "../../../Entities/src/controller/ContentTypesList.js",
  "Entities.controller.EntitiesDetails": "../../../Entities/src/controller/EntitiesDetails.js",
  "Entities.controller.EntitiesGrid": "../../../Entities/src/controller/EntitiesGrid.js",
  "Entities.controller.EntitiesPanel": "../../../Entities/src/controller/EntitiesPanel.js",
  "Entities.controller.EntitiesWindow": "../../../Entities/src/controller/EntitiesWindow.js",
  "Entities.controller.EntityChooser": "../../../Entities/src/controller/EntityChooser.js",
  "Entities.data.Image": "../../../Entities/src/data/Link.js",
  "Entities.data.Link": "../../../Entities/src/data/Image.js",
  "Entities.data.Reference": "../../../Entities/src/data/Reference.js",
  "Entities.model.ContentTypes": "../../../Entities/src/model/ContentTypes.js",
  "Entities.proxy.Entity": "../../../Entities/src/proxy/Entity.js",
  "Entities.service.EntityModelManager": "../../../Entities/src/service/EntityModelManager.js",
  "Entities.store.ContentTypes": "../../../Entities/src/store/ContentTypes.js",
  "Entities.store.Entities": "../../../Entities/src/store/Entities.js",
  "Entities.view.ContentTypesList": "../../../Entities/src/view/ContentTypesList.js",
  "Entities.view.EntitiesDetails": "../../../Entities/src/view/EntitiesDetails.js",
  "Entities.view.EntitiesGrid": "../../../Entities/src/view/EntitiesGrid.js",
  "Entities.view.EntitiesPanel": "../../../Entities/src/view/EntitiesPanel.js",
  "Entities.view.EntitiesWindow": "../../../Entities/src/view/EntitiesWindow.js",
  "Entities.view.EntityChooser": "../../../Entities/src/view/EntityChooser.js",
  "Entities.view.EntityList": "../../../Entities/src/view/EntityList.js",
  "Ext": "../../../../ext/src",
  "Ext.Msg": "../../../../ext/src/window/MessageBox.js",
  "Ext.rtl.EventObjectImpl": "../../../../ext/src/rtl/EventObject.js",
  "Ext.ux.colorpicker": "../../../Shared/src/ux/colorpicker",
  "Fields.controller.Base": "../../../Fields/src/controller/Base.js",
  "Fields.editor.Entity": "../../../Fields/src/editor/Entity.js",
  "Fields.editor.Hidden": "../../../Fields/src/editor/Hidden.js",
  "Fields.editor.Image": "../../../Fields/src/editor/Image.js",
  "Fields.editor.Link": "../../../Fields/src/editor/Link.js",
  "Fields.editor.Number": "../../../Fields/src/editor/Number.js",
  "Fields.editor.Page": "../../../Fields/src/editor/Page.js",
  "Fields.editor.Reference": "../../../Fields/src/editor/Reference.js",
  "Fields.editor.Text": "../../../Fields/src/editor/Text.js",
  "Fields.filters.like": "../../../Fields/src/filters/Like.js",
  "Fields.grid.Image": "../../../Fields/src/grid/Image.js",
  "Fields.grid.Link": "../../../Fields/src/grid/Link.js",
  "Shared": "../../../Shared",
  "Shared.data.reader.CachedJson": "../../../Shared/src/data/reader/CachedJson.js",
  "Shared.model.Image": "../../../Shared/src/model/Image.js",
  "Shared.model.ImageDetails": "../../../Shared/src/model/ImageDetails.js",
  "Shared.model.ImageDetailsBig": "../../../Shared/src/model/ImageDetailsBig.js",
  "Shared.model.ImageDetailsReference": "../../../Shared/src/model/ImageDetailsReference.js",
  "Shared.model.ImageDetailsSmall": "../../../Shared/src/model/ImageDetailsSmall.js",
  "Shared.model.Link": "../../../Shared/src/model/Link.js",
  "Shared.service.Image": "../../../Shared/src/service/Image.js",
  "Shared.service.Link": "../../../Shared/src/service/Link.js",
  "Shared.store.DefaultLinks": "../../../Shared/src/store/DefaultLinks.js",
  "Shared.util.FileUpload": "../../../Shared/src/util/FileUpload.js",
  "Shared.util.TreeColumn": "../../../Shared/src/util/TreeColumn.js",
  "Shared.util.TreeEditing": "../../../Shared/src/util/TreeEditing.js",
  "Shared.util.TypedTreeColumn": "../../../Shared/src/util/TypedTreeColumn.js",
  "Shared.view.ViewDropZone": "../../../Shared/overrides/ViewDropZone.js",
  "Shared.view.Window": "../../../Shared/src/view/Window.js",
  "Siteeditor": "../../src",
  "Siteeditor.controller.ControllerTreeEditor": "../../src/controller/SectionTreeEditor.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Deft.Component": [],
  "Deft.InjectableComponent": [],
  "Deft.core.Class": [
    "Deft.Class"
  ],
  "Deft.event.LiveEventBus": [
    "Deft.LiveEventBus"
  ],
  "Deft.event.LiveEventListener": [
    "Deft.LiveEventListener"
  ],
  "Deft.ioc.DependencyProvider": [],
  "Deft.ioc.Injector": [
    "Deft.Injector"
  ],
  "Deft.log.Logger": [
    "Deft.Logger"
  ],
  "Deft.mixin.Controllable": [],
  "Deft.mixin.Injectable": [],
  "Deft.mvc.Application": [
    "Deft.Application"
  ],
  "Deft.mvc.ComponentSelector": [],
  "Deft.mvc.ComponentSelectorListener": [],
  "Deft.mvc.Observer": [],
  "Deft.mvc.ViewController": [
    "Deft.ViewController"
  ],
  "Deft.promise.Chain": [
    "Deft.Chain"
  ],
  "Deft.promise.Consequence": [
    "Deft.Consequence"
  ],
  "Deft.promise.Deferred": [
    "Deft.Deferred"
  ],
  "Deft.promise.Promise": [
    "Deft.Promise"
  ],
  "Deft.promise.Resolver": [
    "Deft.Resolver"
  ],
  "Deft.util.Function": [
    "Deft.Function"
  ],
  "Entities.app.App": [],
  "Entities.controller.ContentTypesList": [],
  "Entities.controller.EntitiesDetails": [],
  "Entities.controller.EntitiesGrid": [],
  "Entities.controller.EntitiesPanel": [],
  "Entities.controller.EntitiesWindow": [],
  "Entities.controller.EntityChooser": [],
  "Entities.data.Image": [],
  "Entities.data.Link": [],
  "Entities.data.Reference": [],
  "Entities.model.ContentTypes": [],
  "Entities.proxy.Entity": [],
  "Entities.service.EntityModelManager": [],
  "Entities.store.ContentTypes": [],
  "Entities.store.Entities": [],
  "Entities.view.ContentTypesList": [],
  "Entities.view.EntitiesDetails": [],
  "Entities.view.EntitiesGrid": [],
  "Entities.view.EntitiesPanel": [],
  "Entities.view.EntitiesWindow": [],
  "Entities.view.EntityChooser": [],
  "Entities.view.EntityList": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.GMapPanel": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.GroupTabRenderer": [],
  "Ext.ux.IFrame": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.PreviewPlugin": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.TabCloseMenu": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.TreePicker": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.colorpicker.ColorPicker": [],
  "Ext.ux.colorpicker.ColorPickerField": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.layout.Center": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Fields.controller.Base": [],
  "Fields.editor.Entity": [],
  "Fields.editor.Hidden": [],
  "Fields.editor.Image": [],
  "Fields.editor.Link": [],
  "Fields.editor.Number": [],
  "Fields.editor.Page": [],
  "Fields.editor.Reference": [],
  "Fields.editor.Text": [],
  "Fields.filters.like": [],
  "Fields.grid.Image": [],
  "Fields.grid.Link": [],
  "Shared.data.reader.CachedJson": [],
  "Shared.model.Image": [],
  "Shared.model.ImageDetails": [],
  "Shared.model.ImageDetailsBig": [],
  "Shared.model.ImageDetailsReference": [],
  "Shared.model.ImageDetailsSmall": [],
  "Shared.model.Link": [],
  "Shared.overrides.CellEditor": [],
  "Shared.overrides.DragZone": [],
  "Shared.overrides.Editor": [],
  "Shared.overrides.Model": [],
  "Shared.overrides.TreeStore": [],
  "Shared.service.Image": [],
  "Shared.service.Link": [],
  "Shared.store.DefaultLinks": [],
  "Shared.util.FileUpload": [],
  "Shared.util.TreeColumn": [],
  "Shared.util.TreeEditing": [],
  "Shared.util.TypedTreeColumn": [],
  "Shared.view.ViewDropZone": [],
  "Shared.view.Window": [],
  "Siteeditor.app.App": [],
  "Siteeditor.controller.ComponentTree": [],
  "Siteeditor.controller.ControllerTreeEditor": [],
  "Siteeditor.controller.EditorWindow": [],
  "Siteeditor.controller.PropertiesPanel": [],
  "Siteeditor.controller.UrlChooser": [],
  "Siteeditor.controller.UrlCreator": [],
  "Siteeditor.helpers.Window": [],
  "Siteeditor.helpers.window.DropZone": [],
  "Siteeditor.helpers.window.Events": [],
  "Siteeditor.helpers.window.History": [],
  "Siteeditor.helpers.window.Mouse": [],
  "Siteeditor.model.ControllerChilds": [],
  "Siteeditor.model.Controllers": [],
  "Siteeditor.model.Route": [],
  "Siteeditor.model.SectionTree": [],
  "Siteeditor.model.UrlQuery": [],
  "Siteeditor.model.modelTree.Abstract": [],
  "Siteeditor.model.modelTree.List": [],
  "Siteeditor.model.modelTree.Model": [],
  "Siteeditor.model.modelTree.SectionList": [],
  "Siteeditor.store.ModelTree": [],
  "Siteeditor.store.SectionTree": [],
  "Siteeditor.store.UrlSearch": [],
  "Siteeditor.view.ComponentTree": [],
  "Siteeditor.view.DragDropHandle": [],
  "Siteeditor.view.EditorWindow": [],
  "Siteeditor.view.IFrame": [],
  "Siteeditor.view.Properties": [],
  "Siteeditor.view.SectionTree": [],
  "Siteeditor.view.SectionTreeEditor": [],
  "Siteeditor.view.UrlChooser": [],
  "Siteeditor.view.UrlCreator": [],
  "Siteeditor.view.UrlField": []
});
Ext.ClassManager.addNameAliasMappings({
  "Deft.Component": [],
  "Deft.InjectableComponent": [],
  "Deft.core.Class": [],
  "Deft.event.LiveEventBus": [],
  "Deft.event.LiveEventListener": [],
  "Deft.ioc.DependencyProvider": [],
  "Deft.ioc.Injector": [],
  "Deft.log.Logger": [],
  "Deft.mixin.Controllable": [],
  "Deft.mixin.Injectable": [],
  "Deft.mvc.Application": [],
  "Deft.mvc.ComponentSelector": [],
  "Deft.mvc.ComponentSelectorListener": [],
  "Deft.mvc.Observer": [],
  "Deft.mvc.ViewController": [],
  "Deft.promise.Chain": [],
  "Deft.promise.Consequence": [],
  "Deft.promise.Deferred": [],
  "Deft.promise.Promise": [],
  "Deft.promise.Resolver": [],
  "Deft.util.Function": [],
  "Entities.app.App": [],
  "Entities.controller.ContentTypesList": [],
  "Entities.controller.EntitiesDetails": [],
  "Entities.controller.EntitiesGrid": [],
  "Entities.controller.EntitiesPanel": [],
  "Entities.controller.EntitiesWindow": [],
  "Entities.controller.EntityChooser": [],
  "Entities.data.Image": [],
  "Entities.data.Link": [],
  "Entities.data.Reference": [],
  "Entities.model.ContentTypes": [],
  "Entities.proxy.Entity": [
    "proxy.entity"
  ],
  "Entities.service.EntityModelManager": [],
  "Entities.store.ContentTypes": [],
  "Entities.store.Entities": [],
  "Entities.view.ContentTypesList": [
    "widget.cmf_entities_contenttypeslist"
  ],
  "Entities.view.EntitiesDetails": [
    "widget.entities_entitiesdetails"
  ],
  "Entities.view.EntitiesGrid": [
    "widget.entities_entitiesgrid"
  ],
  "Entities.view.EntitiesPanel": [
    "widget.entities_entitiespanel"
  ],
  "Entities.view.EntitiesWindow": [
    "widget.entities_entitieswindow"
  ],
  "Entities.view.EntityChooser": [
    "widget.entities_entitychooser"
  ],
  "Entities.view.EntityList": [
    "widget.entities_entitylist"
  ],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.colorpicker.ColorPicker": [
    "widget.ux.colorpicker"
  ],
  "Ext.ux.colorpicker.ColorPickerField": [
    "widget.ux.colorpickerfield"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Fields.controller.Base": [],
  "Fields.editor.Entity": [
    "widget.fields_editor_entity"
  ],
  "Fields.editor.Hidden": [
    "widget.fields_editor_hidden"
  ],
  "Fields.editor.Image": [
    "widget.fields_editor_image"
  ],
  "Fields.editor.Link": [
    "widget.fields_editor_link"
  ],
  "Fields.editor.Number": [
    "widget.fields_editor_number"
  ],
  "Fields.editor.Page": [
    "widget.fields_editor_page"
  ],
  "Fields.editor.Reference": [
    "widget.fields_editor_reference"
  ],
  "Fields.editor.Text": [
    "widget.fields_editor_text"
  ],
  "Fields.filters.like": [
    "gridfilter.cmf_like"
  ],
  "Fields.grid.Image": [
    "widget.fields_grid_image"
  ],
  "Fields.grid.Link": [
    "widget.fields_grid_link"
  ],
  "Shared.data.reader.CachedJson": [
    "reader.cachedjson"
  ],
  "Shared.model.Image": [],
  "Shared.model.ImageDetails": [],
  "Shared.model.ImageDetailsBig": [],
  "Shared.model.ImageDetailsReference": [],
  "Shared.model.ImageDetailsSmall": [],
  "Shared.model.Link": [],
  "Shared.overrides.CellEditor": [],
  "Shared.overrides.DragZone": [],
  "Shared.overrides.Editor": [],
  "Shared.overrides.Model": [],
  "Shared.overrides.TreeStore": [],
  "Shared.service.Image": [],
  "Shared.service.Link": [],
  "Shared.store.DefaultLinks": [],
  "Shared.util.FileUpload": [],
  "Shared.util.TreeColumn": [],
  "Shared.util.TreeEditing": [
    "plugin.treeediting"
  ],
  "Shared.util.TypedTreeColumn": [
    "widget.cmf_typedtreecolumn"
  ],
  "Shared.view.ViewDropZone": [],
  "Shared.view.Window": [
    "widget.shared-window"
  ],
  "Siteeditor.app.App": [],
  "Siteeditor.controller.ComponentTree": [],
  "Siteeditor.controller.ControllerTreeEditor": [],
  "Siteeditor.controller.EditorWindow": [],
  "Siteeditor.controller.PropertiesPanel": [],
  "Siteeditor.controller.UrlChooser": [],
  "Siteeditor.controller.UrlCreator": [],
  "Siteeditor.helpers.Window": [],
  "Siteeditor.helpers.window.DropZone": [],
  "Siteeditor.helpers.window.Events": [],
  "Siteeditor.helpers.window.History": [],
  "Siteeditor.helpers.window.Mouse": [],
  "Siteeditor.model.ControllerChilds": [],
  "Siteeditor.model.Controllers": [],
  "Siteeditor.model.Route": [],
  "Siteeditor.model.SectionTree": [],
  "Siteeditor.model.UrlQuery": [],
  "Siteeditor.model.modelTree.Abstract": [],
  "Siteeditor.model.modelTree.List": [],
  "Siteeditor.model.modelTree.Model": [],
  "Siteeditor.model.modelTree.SectionList": [],
  "Siteeditor.store.ModelTree": [],
  "Siteeditor.store.SectionTree": [],
  "Siteeditor.store.UrlSearch": [],
  "Siteeditor.view.ComponentTree": [
    "widget.cmf_siteeditor_componenttree"
  ],
  "Siteeditor.view.DragDropHandle": [
    "widget.cmf_siteeditor_dragdrophandle"
  ],
  "Siteeditor.view.EditorWindow": [
    "widget.cmf_siteeditor_editorwindow"
  ],
  "Siteeditor.view.IFrame": [
    "widget.siteeditor_iframe"
  ],
  "Siteeditor.view.Properties": [
    "widget.cmf_siteeditor_properties"
  ],
  "Siteeditor.view.SectionTree": [
    "widget.cmf_siteeditor_sectiontree"
  ],
  "Siteeditor.view.SectionTreeEditor": [
    "widget.cmf_siteeditor_sectiontreeeditor"
  ],
  "Siteeditor.view.UrlChooser": [
    "widget.siteeditor_urlchooser"
  ],
  "Siteeditor.view.UrlCreator": [],
  "Siteeditor.view.UrlField": [
    "widget.cmf_urlfield"
  ]
});
Ext.Loader.loadScript("../../../Shared/overrides/Editor.js");
Ext.Loader.loadScript("../../../Shared/overrides/Model.js");
Ext.Loader.loadScript("../../../Shared/overrides/TreeStore.js");
Ext.Loader.loadScript("../../../Shared/overrides/CellEditor.js");
Ext.Loader.loadScript("../../../Shared/overrides/DragZone.js");
Ext.Loader.loadScript("../../../Shared/overrides/ViewDropZone.js");
