
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Deft": "../../../deft/src/js",
  "Deft.InjectableComponent": "../../../deft/src/js/ioc/Injector.js",
  "Ext": "../../../../ext/src",
  "Ext.Msg": "../../../../ext/src/window/MessageBox.js",
  "Ext.rtl.EventObjectImpl": "../../../../ext/src/rtl/EventObject.js",
  "Ext.ux.colorpicker": "../../../Shared/src/ux/colorpicker",
  "Images": "../../src",
  "Images.store.Images": "../../src/store/Images.js",
  "Shared": "../../../Shared",
  "Shared.data.reader.CachedJson": "../../../Shared/src/data/reader/CachedJson.js",
  "Shared.model.Image": "../../../Shared/src/model/Image.js",
  "Shared.model.ImageDetails": "../../../Shared/src/model/ImageDetails.js",
  "Shared.model.ImageDetailsBig": "../../../Shared/src/model/ImageDetailsBig.js",
  "Shared.model.ImageDetailsReference": "../../../Shared/src/model/ImageDetailsReference.js",
  "Shared.model.ImageDetailsSmall": "../../../Shared/src/model/ImageDetailsSmall.js",
  "Shared.model.Link": "../../../Shared/src/model/Link.js",
  "Shared.service.Image": "../../../Shared/src/service/Image.js",
  "Shared.service.Link": "../../../Shared/src/service/Link.js",
  "Shared.store.DefaultLinks": "../../../Shared/src/store/DefaultLinks.js",
  "Shared.util.FileUpload": "../../../Shared/src/util/FileUpload.js",
  "Shared.util.TreeColumn": "../../../Shared/src/util/TreeColumn.js",
  "Shared.util.TreeEditing": "../../../Shared/src/util/TreeEditing.js",
  "Shared.util.TypedTreeColumn": "../../../Shared/src/util/TypedTreeColumn.js",
  "Shared.view.ViewDropZone": "../../../Shared/overrides/ViewDropZone.js",
  "Shared.view.Window": "../../../Shared/src/view/Window.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Deft.InjectableComponent": [],
  "Deft.core.Class": [
    "Deft.Class"
  ],
  "Deft.core.Component": [
    "Deft.Component"
  ],
  "Deft.event.LiveEventBus": [
    "Deft.LiveEventBus"
  ],
  "Deft.event.LiveEventListener": [
    "Deft.LiveEventListener"
  ],
  "Deft.ioc.DependencyProvider": [],
  "Deft.ioc.Injector": [
    "Deft.Injector"
  ],
  "Deft.log.Logger": [
    "Deft.Logger"
  ],
  "Deft.mixin.Controllable": [],
  "Deft.mixin.Injectable": [],
  "Deft.mvc.Application": [
    "Deft.Application"
  ],
  "Deft.mvc.ComponentSelector": [],
  "Deft.mvc.ComponentSelectorListener": [],
  "Deft.mvc.Observer": [],
  "Deft.mvc.ViewController": [
    "Deft.ViewController"
  ],
  "Deft.promise.Chain": [
    "Deft.Chain"
  ],
  "Deft.promise.Deferred": [
    "Deft.Deferred"
  ],
  "Deft.promise.Promise": [
    "Deft.Promise"
  ],
  "Deft.promise.Resolver": [
    "Deft.Resolver"
  ],
  "Deft.util.Function": [
    "Deft.Function"
  ],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.GMapPanel": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.GroupTabRenderer": [],
  "Ext.ux.IFrame": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.PreviewPlugin": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.TabCloseMenu": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.TreePicker": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.colorpicker.ColorPicker": [],
  "Ext.ux.colorpicker.ColorPickerField": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.layout.Center": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Images.app.App": [],
  "Images.controller.DnDImageTable": [],
  "Images.controller.DraggableImageView": [],
  "Images.controller.ImageBrowser": [],
  "Images.controller.ImageTreeEditor": [],
  "Images.controller.ImageUploader": [],
  "Images.model.ImageQuery": [],
  "Images.model.ImageUpload": [],
  "Images.store.DnDImageTable": [],
  "Images.store.ImageTree": [],
  "Images.store.Images": [],
  "Images.view.DnDImageTable": [],
  "Images.view.DraggableImageView": [],
  "Images.view.ImageBrowser": [],
  "Images.view.ImageChooser": [],
  "Images.view.ImageTree": [],
  "Images.view.ImageTreeEditor": [],
  "Images.view.ImageUploader": [],
  "Images.view.ImageUploaderDetails": [],
  "Images.view.ImageView": [],
  "Images.view.SystemStatus": [],
  "Shared.data.reader.CachedJson": [],
  "Shared.model.Image": [],
  "Shared.model.ImageDetails": [],
  "Shared.model.ImageDetailsBig": [],
  "Shared.model.ImageDetailsReference": [],
  "Shared.model.ImageDetailsSmall": [],
  "Shared.model.Link": [],
  "Shared.overrides.CellEditor": [],
  "Shared.overrides.DragZone": [],
  "Shared.overrides.Editor": [],
  "Shared.overrides.Model": [],
  "Shared.overrides.TreeStore": [],
  "Shared.service.Image": [],
  "Shared.service.Link": [],
  "Shared.store.DefaultLinks": [],
  "Shared.util.FileUpload": [],
  "Shared.util.TreeColumn": [],
  "Shared.util.TreeEditing": [],
  "Shared.util.TypedTreeColumn": [],
  "Shared.view.ViewDropZone": [],
  "Shared.view.Window": []
});
Ext.ClassManager.addNameAliasMappings({
  "Deft.InjectableComponent": [],
  "Deft.core.Class": [],
  "Deft.core.Component": [],
  "Deft.event.LiveEventBus": [],
  "Deft.event.LiveEventListener": [],
  "Deft.ioc.DependencyProvider": [],
  "Deft.ioc.Injector": [],
  "Deft.log.Logger": [],
  "Deft.mixin.Controllable": [],
  "Deft.mixin.Injectable": [],
  "Deft.mvc.Application": [],
  "Deft.mvc.ComponentSelector": [],
  "Deft.mvc.ComponentSelectorListener": [],
  "Deft.mvc.Observer": [],
  "Deft.mvc.ViewController": [],
  "Deft.promise.Chain": [],
  "Deft.promise.Deferred": [],
  "Deft.promise.Promise": [],
  "Deft.promise.Resolver": [],
  "Deft.util.Function": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.colorpicker.ColorPicker": [
    "widget.ux.colorpicker"
  ],
  "Ext.ux.colorpicker.ColorPickerField": [
    "widget.ux.colorpickerfield"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Images.app.App": [],
  "Images.controller.DnDImageTable": [],
  "Images.controller.DraggableImageView": [],
  "Images.controller.ImageBrowser": [],
  "Images.controller.ImageTreeEditor": [],
  "Images.controller.ImageUploader": [],
  "Images.model.ImageQuery": [],
  "Images.model.ImageUpload": [],
  "Images.store.DnDImageTable": [],
  "Images.store.ImageTree": [],
  "Images.store.Images": [],
  "Images.view.DnDImageTable": [
    "widget.cmf_images_dndimagetable"
  ],
  "Images.view.DraggableImageView": [
    "widget.cmf_images_draggableimageview"
  ],
  "Images.view.ImageBrowser": [
    "widget.cmf_images_imagebrowser"
  ],
  "Images.view.ImageChooser": [
    "widget.cmf_images_imagechooser"
  ],
  "Images.view.ImageTree": [
    "widget.cmf_images_imagetree"
  ],
  "Images.view.ImageTreeEditor": [
    "widget.cmf_images_imagetreeeditor"
  ],
  "Images.view.ImageUploader": [
    "widget.cmf_image_imageuploader"
  ],
  "Images.view.ImageUploaderDetails": [
    "widget.cmf_images_imageuploaderdetails"
  ],
  "Images.view.ImageView": [
    "widget.cmf_images_imageview"
  ],
  "Images.view.SystemStatus": [],
  "Shared.data.reader.CachedJson": [
    "reader.cachedjson"
  ],
  "Shared.model.Image": [],
  "Shared.model.ImageDetails": [],
  "Shared.model.ImageDetailsBig": [],
  "Shared.model.ImageDetailsReference": [],
  "Shared.model.ImageDetailsSmall": [],
  "Shared.model.Link": [],
  "Shared.overrides.CellEditor": [],
  "Shared.overrides.DragZone": [],
  "Shared.overrides.Editor": [],
  "Shared.overrides.Model": [],
  "Shared.overrides.TreeStore": [],
  "Shared.service.Image": [],
  "Shared.service.Link": [],
  "Shared.store.DefaultLinks": [],
  "Shared.util.FileUpload": [],
  "Shared.util.TreeColumn": [],
  "Shared.util.TreeEditing": [
    "plugin.treeediting"
  ],
  "Shared.util.TypedTreeColumn": [
    "widget.cmf_typedtreecolumn"
  ],
  "Shared.view.ViewDropZone": [],
  "Shared.view.Window": [
    "widget.shared-window"
  ]
});
Ext.Loader.loadScript("../../../Shared/overrides/Editor.js");
Ext.Loader.loadScript("../../../Shared/overrides/Model.js");
Ext.Loader.loadScript("../../../Shared/overrides/TreeStore.js");
Ext.Loader.loadScript("../../../Shared/overrides/CellEditor.js");
Ext.Loader.loadScript("../../../Shared/overrides/DragZone.js");
Ext.Loader.loadScript("../../../Shared/overrides/ViewDropZone.js");
